#指定注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
  
spring:
  application:
    name: service-ali1 #spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name